[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
